# Generated by Django 6.0.2 on 2026-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_payment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código de grupo para reservas vinculadas', max_length=10),
        ),
    ]
