# Generated by Django 6.0.2 on 2026-02-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='operational_status',
            field=models.CharField(choices=[('incomplete', 'Incompleta'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('cancelled', 'Cancelada'), ('no_show', 'No-show')], default='incomplete', max_length=20),
        ),
    ]
