# Generated by Django 6.0.2 on 2026-02-15 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_add_critical_indexes'),
        ('organizations', '0011_bank_account_org_level'),
        ('reservations', '0004_add_incomplete_operational_status'),
        ('rooms', '0007_add_critical_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='financial_status',
            field=models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('partial', 'Parcial'), ('paid', 'Pagada'), ('partial_refund', 'Reembolso parcial'), ('refunded', 'Reembolsada')], db_index=True, default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='operational_status',
            field=models.CharField(choices=[('incomplete', 'Incompleta'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('cancelled', 'Cancelada'), ('no_show', 'No-show')], db_index=True, default='incomplete', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'operational_status', 'check_in_date', 'check_out_date'], name='res_avail_lookup'),
        ),
    ]
