# Generated by Django 5.1.15 on 2026-02-08 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BedConfigurationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_type', models.CharField(choices=[('single', 'Individual'), ('double', 'Doble'), ('queen', 'Queen'), ('king', 'King'), ('bunk', 'Litera'), ('sofa_bed', 'Sofá cama')], max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('bed_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='rooms.bedconfiguration')),
            ],
            options={
                'ordering': ['bed_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='organizations.property')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('property', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='bedconfiguration',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_configurations', to='rooms.roomtype'),
        ),
        migrations.CreateModel(
            name='RoomTypePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('dirty', 'Sucia'), ('cleaning', 'En limpieza'), ('inspection', 'En inspección'), ('blocked', 'Bloqueada'), ('maintenance', 'Mantenimiento')], default='available', max_length=20)),
                ('active_bed_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_rooms', to='rooms.bedconfiguration')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organizations.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('property', 'number')},
            },
        ),
    ]
