# Generated by Django 5.1.15 on 2026-02-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtypephoto',
            name='url',
        ),
        migrations.AddField(
            model_name='roomtypephoto',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='room_types/'),
            preserve_default=False,
        ),
    ]
