# Generated by Django 5.1.15 on 2026-02-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_m2m_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('private_shower', 'Baño privado con ducha'), ('private_tub', 'Baño privado con tina'), ('private_jacuzzi', 'Baño privado con jacuzzi'), ('shared', 'Baño compartido')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='view_type',
            field=models.CharField(blank=True, choices=[('garden', 'Jardín'), ('ocean', 'Mar'), ('city', 'Ciudad'), ('mountain', 'Montaña'), ('pool', 'Piscina'), ('interior', 'Interior')], default='', max_length=50),
        ),
    ]
