# Generated by Django 6.0.2 on 2026-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtype_bathroom_type_roomtype_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='extra_adult_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo adicional por noche por cada adulto despues del primero', max_digits=10),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_child_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo adicional por noche por cada nino', max_digits=10),
        ),
    ]
