# Generated by Django 6.0.2 on 2026-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomtype_extra_adult_fee_roomtype_extra_child_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='base_occupancy',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de adultos incluidos en el precio base'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='extra_adult_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo adicional por noche por cada adulto extra', max_digits=10),
        ),
    ]
