# Generated by Django 6.0.2 on 2026-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomtype_base_occupancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('dirty', 'Sucia'), ('cleaning', 'En limpieza'), ('inspection', 'En inspección'), ('blocked', 'Bloqueada'), ('maintenance', 'Mantenimiento')], db_index=True, default='available', max_length=20),
        ),
    ]
