# Generated by Django 5.1.15 on 2026-02-08 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('field', models.CharField(default='status', max_length=100)),
                ('old_value', models.CharField(max_length=50)),
                ('new_value', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
