# Generated by Django 5.1.15 on 2026-02-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['start_month', 'start_day']},
        ),
        migrations.RemoveField(
            model_name='season',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='season',
            name='start_date',
        ),
        migrations.AddField(
            model_name='season',
            name='end_day',
            field=models.PositiveSmallIntegerField(default=31, help_text='1-31'),
        ),
        migrations.AddField(
            model_name='season',
            name='end_month',
            field=models.PositiveSmallIntegerField(default=12, help_text='1-12'),
        ),
        migrations.AddField(
            model_name='season',
            name='start_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-31'),
        ),
        migrations.AddField(
            model_name='season',
            name='start_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-12'),
        ),
    ]
