# Generated by Django 5.1.15 on 2026-02-08 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(choices=[('reservation.created', 'Reserva creada'), ('reservation.confirmed', 'Reserva confirmada'), ('reservation.check_in', 'Check-in'), ('reservation.check_out', 'Check-out'), ('reservation.cancelled', 'Reserva cancelada'), ('reservation.no_show', 'No-show'), ('payment.received', 'Pago recibido'), ('room.status_changed', 'Cambio estado habitación'), ('task.completed', 'Tarea completada'), ('guest.created', 'Huésped creado')], max_length=50)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(default=list)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Reglas del sistema no pueden ser eliminadas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=200)),
                ('trigger', models.CharField(max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('conditions_met', models.BooleanField(default=True)),
                ('actions_executed', models.JSONField(default=list)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
