# Generated by Django 6.0.2 on 2026-02-14 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0004_guest_is_verified_guest_last_login'),
        ('organizations', '0011_bank_account_org_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('event_name', models.CharField(db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='guests.guest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event_name'], name='events_even_organiz_bf8a84_idx'), models.Index(fields=['organization', 'created_at'], name='events_even_organiz_7e6708_idx'), models.Index(fields=['organization', 'session_id'], name='events_even_organiz_406128_idx')],
            },
        ),
    ]
