# Generated by Django 5.1.15 on 2026-02-12 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_bankaccount'),
        ('reservations', '0002_reservation_payment_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_mode', models.CharField(choices=[('disabled', 'Deshabilitado'), ('manual', 'Manual'), ('automatic', 'Automático')], default='disabled', max_length=20)),
                ('ruc', models.CharField(blank=True, default='', max_length=20)),
                ('razon_social', models.CharField(blank=True, default='', max_length=300)),
                ('direccion_fiscal', models.TextField(blank=True, default='')),
                ('proveedor', models.CharField(blank=True, choices=[('nubefact', 'Nubefact'), ('efact', 'eFact'), ('custom_webhook', 'Custom Webhook')], default='', max_length=30)),
                ('tipo_autenticacion', models.CharField(choices=[('api_key', 'API Key'), ('certificate', 'Certificado Digital'), ('oauth2', 'OAuth2')], default='api_key', max_length=20)),
                ('api_endpoint', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('certificado_digital', models.FileField(blank=True, upload_to='billing/certificates/')),
                ('ambiente', models.CharField(choices=[('produccion', 'Produccion'), ('beta', 'Beta')], default='beta', max_length=20)),
                ('configuracion_tributaria', models.JSONField(blank=True, default=dict)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Configuracion de facturacion',
                'verbose_name_plural': 'Configuraciones de facturacion',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('nota_credito', 'Nota de credito'), ('nota_debito', 'Nota de debito')], max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.PositiveIntegerField()),
                ('numero_completo', models.CharField(editable=False, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('voided', 'Anulado'), ('error', 'Error')], default='draft', max_length=20)),
                ('cliente_tipo_documento', models.CharField(blank=True, default='', max_length=10)),
                ('cliente_numero_documento', models.CharField(blank=True, default='', max_length=20)),
                ('cliente_razon_social', models.CharField(blank=True, default='', max_length=300)),
                ('cliente_direccion', models.CharField(blank=True, default='', max_length=500)),
                ('cliente_email', models.EmailField(blank=True, default='', max_length=254)),
                ('total_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_exonerado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_inafecto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('provider_request', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('provider_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_error_code', models.CharField(blank=True, default='', max_length=50)),
                ('provider_document_url', models.URLField(blank=True, default='')),
                ('sunat_ticket', models.CharField(blank=True, default='', max_length=100)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.property')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_documents', to='billing.invoice')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'serie', 'correlativo')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_afectacion_igv', models.CharField(choices=[('10', 'Gravado'), ('20', 'Exonerado'), ('30', 'Inafecto')], default='10', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBillingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usa_configuracion_propia', models.BooleanField(default=False)),
                ('emission_mode', models.CharField(choices=[('inherit', 'Heredar de organización'), ('disabled', 'Deshabilitado'), ('manual', 'Manual'), ('automatic', 'Automático')], default='inherit', max_length=20)),
                ('proveedor', models.CharField(blank=True, choices=[('nubefact', 'Nubefact'), ('efact', 'eFact'), ('custom_webhook', 'Custom Webhook')], default='', max_length=30)),
                ('api_endpoint', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('serie_boleta', models.CharField(blank=True, default='', max_length=10)),
                ('serie_factura', models.CharField(blank=True, default='', max_length=10)),
                ('establecimiento_codigo', models.CharField(blank=True, default='', max_length=10)),
                ('punto_emision', models.CharField(blank=True, default='', max_length=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='organizations.property')),
            ],
            options={
                'verbose_name': 'Configuracion de facturacion por propiedad',
                'verbose_name_plural': 'Configuraciones de facturacion por propiedad',
            },
        ),
    ]
