# Generated by Django 6.0.2 on 2026-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
