# Generated by Django 6.0.2 on 2026-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
