# Generated by Django 6.0.2 on 2026-02-15 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_is_verified_guest_last_login'),
        ('organizations', '0011_bank_account_org_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['organization', 'document_type', 'document_number'], name='guest_doc_lookup'),
        ),
    ]
