from django.urls import path

from . import views
from apps.events.views import EventIngestView

urlpatterns = [
    path(
        "resolve-domain/",
        views.ResolveDomainView.as_view(),
        name="public-resolve-domain",
    ),
    path(
        "hotels/",
        views.PublicHotelSearchView.as_view(),
        name="public-hotel-search",
    ),
    path(
        "register-hotel/",
        views.RegisterHotelView.as_view(),
        name="public-register-hotel",
    ),
    path(
        "contact/",
        views.ContactView.as_view(),
        name="public-contact",
    ),
    path(
        "<slug:org_slug>/info/",
        views.OrganizationInfoView.as_view(),
        name="public-org-info",
    ),
    path(
        "<slug:org_slug>/room-types/",
        views.RoomTypeListView.as_view(),
        name="public-room-types",
    ),
    path(
        "<slug:org_slug>/room-types/<uuid:room_type_id>/",
        views.RoomTypeDetailView.as_view(),
        name="public-room-type-detail",
    ),
    path(
        "<slug:org_slug>/availability/",
        views.AvailabilityView.as_view(),
        name="public-availability",
    ),
    path(
        "<slug:org_slug>/reservations/",
        views.CreateReservationView.as_view(),
        name="public-create-reservation",
    ),
    path(
        "<slug:org_slug>/reservations/group/",
        views.CreateGroupReservationView.as_view(),
        name="public-create-group-reservation",
    ),
    path(
        "<slug:org_slug>/reservations/<str:confirmation_code>/",
        views.ReservationLookupView.as_view(),
        name="public-reservation-lookup",
    ),
    path(
        "<slug:org_slug>/bank-accounts/",
        views.BankAccountListView.as_view(),
        name="public-bank-accounts",
    ),
    path(
        "<slug:org_slug>/reservations/<str:confirmation_code>/voucher/",
        views.VoucherUploadView.as_view(),
        name="public-voucher-upload",
    ),
    path(
        "<slug:org_slug>/guest-register/",
        views.GuestRegisterView.as_view(),
        name="public-guest-register",
    ),
    path(
        "<slug:org_slug>/guest-login/",
        views.GuestLoginView.as_view(),
        name="public-guest-login",
    ),
    path(
        "<slug:org_slug>/guest/verify-email/",
        views.GuestVerifyEmailView.as_view(),
        name="public-guest-verify-email",
    ),
    path(
        "<slug:org_slug>/guest/lookup/",
        views.GuestLookupView.as_view(),
        name="public-guest-lookup",
    ),
    path(
        "<slug:org_slug>/guest/request-otp/",
        views.GuestRequestOTPView.as_view(),
        name="public-guest-request-otp",
    ),
    path(
        "<slug:org_slug>/guest/identity-data/",
        views.GuestIdentityDataView.as_view(),
        name="public-guest-identity-data",
    ),
    path(
        "<slug:org_slug>/guest/activate/",
        views.GuestActivateView.as_view(),
        name="public-guest-activate",
    ),
    path(
        "<slug:org_slug>/guest-profile/",
        views.GuestProfileView.as_view(),
        name="public-guest-profile",
    ),
    path(
        "<slug:org_slug>/mis-reservas/",
        views.GuestReservationsView.as_view(),
        name="public-guest-reservations",
    ),
    path(
        "<slug:org_slug>/reservations/<str:confirmation_code>/cancel/",
        views.GuestCancelReservationView.as_view(),
        name="public-guest-cancel-reservation",
    ),
    path(
        "<slug:org_slug>/events/",
        EventIngestView.as_view(),
        name="public-events",
    ),
    path(
        "<slug:org_slug>/reniec-lookup/",
        views.PublicReniecLookupView.as_view(),
        name="public-reniec-lookup",
    ),
]
