# Generated by Django 5.1.15 on 2026-02-08 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50)),
                ('timezone', models.CharField(default='America/Lima', max_length=50)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('language', models.CharField(default='es', max_length=10)),
                ('logo', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(default='#1976D2', max_length=7)),
                ('secondary_color', models.CharField(default='#FF9800', max_length=7)),
                ('font', models.CharField(blank=True, default='', max_length=100)),
                ('subdomain', models.CharField(max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.CharField(default='basic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='PE', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='12:00')),
                ('policies', models.JSONField(blank=True, default=dict)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
