# Generated by Django 5.1.15 on 2026-02-09 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='properties/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='organizations.property')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
