# Generated by Django 5.1.15 on 2026-02-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_property_amenities_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='theme_accent_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='property',
            name='theme_palette',
            field=models.CharField(default='navy-gold', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='theme_primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='property',
            name='theme_template',
            field=models.CharField(choices=[('luxury', 'Luxury / Classic'), ('modern', 'Modern / Minimalist'), ('tropical', 'Tropical / Vibrant')], default='luxury', max_length=20),
        ),
    ]
