# Generated by Django 5.1.15 on 2026-02-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_property_theme_accent_color_property_theme_palette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, upload_to='properties/logos/'),
        ),
    ]
