# Generated by Django 5.1.15 on 2026-02-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_property_theme_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
