# Generated by Django 5.1.15 on 2026-02-12 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_add_custom_domain_to_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('cci', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.property')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
