# Generated by Django 6.0.2 on 2026-02-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_property_custom_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='website_url',
        ),
    ]
