# Generated by Django 6.0.2 on 2026-02-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_organization_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='theme_accent_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='theme_palette',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='theme_primary_color',
        ),
    ]
