# Generated by Django 6.0.2 on 2026-02-12 21:14

import django.db.models.deletion
from django.db import migrations, models


def populate_organization(apps, schema_editor):
    """Fill organization from property.organization for existing rows."""
    BankAccount = apps.get_model("organizations", "BankAccount")
    for account in BankAccount.objects.filter(organization__isnull=True).select_related("property"):
        if account.property_id:
            account.organization = account.property.organization
            account.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_remove_theme_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Null = cuenta de la organización, heredada por todas las propiedades', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.property'),
        ),
        migrations.RunPython(populate_organization, migrations.RunPython.noop),
    ]
