# Generated by Django 6.0.2 on 2026-02-14 09:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0004_guest_is_verified_guest_last_login'),
        ('organizations', '0011_bank_account_org_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=20)),
                ('document_hash', models.CharField(help_text='SHA-256 of normalized document_type:document_number', max_length=128, unique=True)),
                ('encrypted_email', models.BinaryField(blank=True, null=True)),
                ('encrypted_name', models.BinaryField(blank=True, null=True)),
                ('encryption_version', models.PositiveSmallIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Identity',
                'verbose_name_plural': 'Global Identities',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='identity.globalidentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_links', to='guests.guest')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='identity.globalidentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'unique_together': {('identity', 'organization')},
            },
        ),
    ]
