# Generated by Django 6.0.2 on 2026-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalidentity',
            name='encrypted_nationality',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalidentity',
            name='encrypted_phone',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
